max_width = 120
reorder_imports = true
indent_style = "Block"
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
group_imports = "StdExternalCrate"