name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-lint:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Cache Rust dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install clippy
      run: rustup component add clippy

    - name: Lint with clippy
      run: cargo clippy --all-features -- -D warnings

    - name: Run tests
      run: cargo test --all-features
